[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
auto_detect_solc = false
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[fmt]
line_length = 100
